resource_group_name = "rg-terraform-sample"
location            = "South India"
storage_account_name = "stterraformsamplesa"
cosmosdb_account_name = "cosdb-terraform-sample"
key_vault_name = "kv-terraform-adithya"
app_configuration_name = "appconf-terraform-sample-adithya"
